### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by jdleung** [mpiannucci/SwiftContour#2]
From the sample 

` let values = [
            [0.0, 0.0, 0.0, 0.0, 0.0],
            [0.0, 1.0, 1.0, 1.0, 0.0],
            [0.0, 1.0, 1.0, 1.0, 0.0],
            [0.0, 1.0, 1.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 0.0]
        ]
        `

The data type is not fit for `public func contours(values: Array<Double>, width: Int, height: Int, thresholds: Array<Double>, smoothing: Bool)`

So I try to change the data type to Array<Double>
        `let data = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]`

And then I got  error **Index out of range** at 
`func _threshold(index: Int) -> Bool `

What did I miss?

**Comment by mpiannucci** [comment]
Can you show what you pass for the width, height and thresholds? k

**Comment by jdleung** [comment]
> Can you show what you pass for the width, height and thresholds? k

I kept them as same as the sample's

```
do {
            let contour = try contours(values: data, width: 10, height: 10, thresholds: [0.5], smoothing: true)
        } catch {
            
        }
```

**Comment by mpiannucci** [comment]
You aren't passing in the width and height of that match your data. The way the algorithm works, if you have a 5x2 array, you would pass 5 for the width and 2 for the height. 

In the examples, the inputs are 5 for both width and height because there are 25 elements 

I need to update the readme, thanks for pointing that out!

**Comment by jdleung** [comment]
OK, it works now. Thanks.
